" avoid side effects when reloading vimrc

if &compatible
	" vint: -ProhibitSetNoCompatible
	set nocompatible
	" vint: +ProhibitSetNoCompatible
endif



let g:ale_disable_lsp = 1
let $VIMPATH = $HOME . '/.vim'
let $CFGPATH = $VIMPATH . '/config'

"ArchLinux plugins that have been installed like dein
set runtimepath+=/usr/share/vim/vimfiles

function! s:SourceConfig(path) abort
  let use_global = get(a:000, 0, ! has('vim_starting'))
  let abspath = resolve($CFGPATH . '/' . a:path)
  if ! use_global
		execute 'source' fnameescape(abspath)
		return
	endif


let tempfile = tempname()
	let content = map(readfile(abspath),
		\ "substitute(v:val, '^\\W*\\zsset\\ze\\W', 'setglobal', '')")
	try
		call writefile(content, tempfile)
		execute printf('source %s', fnameescape(tempfile))
	finally
		if filereadable(tempfile)
			call delete(tempfile)
		endif
	endtry
endfunction

" Initialize startup settings
if has('vim_starting')
	" Use spacebar as leader and ; as secondary-leader
	" Required before loading plugins!
	let g:mapleader="\<Space>"
	let g:maplocalleader=';'

	" Release keymappings prefixes, evict entirely for use of plug-ins.
	nnoremap <Space>  <Nop>
	xnoremap <Space>  <Nop>
	nnoremap ,        <Nop>
	xnoremap ,        <Nop>
	nnoremap ;        <Nop>
	xnoremap ;        <Nop>

	" Vim only, Linux terminal settings
	if ! has('nvim') && ! has('gui_running') && ! has('win32') && ! has('win64')
		call s:SourceConfig(path)('config/terminal.vim')
	endif
endif

" Initialize plugin-manager and load main config files
call s:SourceConfig('init.vim')
call s:SourceConfig('plugins/all.vim')

" Initialize all configurations
call s:SourceConfig('reset.vim')
call s:SourceConfig('general.vim')
call s:SourceConfig('filetypes.vim')
call s:SourceConfig('functions.vim')
call s:SourceConfig('editing.vim')
call s:SourceConfig('display.vim')
call s:SourceConfig('theme.vim')
call s:SourceConfig('shortcuts.vim')
call s:SourceConfig('terminal.vim')

call s:SourceConfig('plugins/coc.vim')

filetype plugin indent on
if !exists('g:syntax_on') | syntax enable | endif

" vim: set filetype=vim foldmethod=marker foldlevel=0 nowrap:
